trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '87913068-9b24-4b1b-a111-e3a6400dd329'
  imageRepository: 'qasimhelloworld'
  containerRegistry: 'qasimsdevop.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'qasimsdevopec8b-auth'
  vmImageName: 'ubuntu-latest'

pool:
  name: DESKTOP-1P4V56D  # Updated to use your local agent pool

jobs:
- job: BuildAndDeploy
  displayName: Build and Deploy
  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)

  - task: KubernetesManifest@0
    displayName: Create imagePullSecret
    inputs:
      action: createSecret
      secretName: $(imagePullSecret)
      dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

  - task: KubernetesManifest@0
    displayName: Deploy to Kubernetes cluster
    inputs:
      action: deploy
      manifests: |
        $(Pipeline.Workspace)/manifests/deployment.yml
        $(Pipeline.Workspace)/manifests/service.yml
      imagePullSecrets: |
        $(imagePullSecret)
      containers: |
        $(containerRegistry)/$(imageRepository):$(tag)
